"""
libAI C++ backend
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['AdaGrad', 'Adam', 'BatchNormalization', 'Dense', 'Dropout', 'HyperparameterTuner', 'Linear', 'MeanSquaredError', 'Momentum', 'NeuralNetwork', 'ReLU', 'SGD', 'Sigmoid', 'SoftmaxCrossEntropy', 'Tanh', 'Tensor', 'Trainer']
class AdaGrad(_Optimizer):
    def __init__(self, learning_rate: typing.SupportsFloat | typing.SupportsIndex = 0.009999999776482582, eps: typing.SupportsFloat | typing.SupportsIndex = 9.99999993922529e-09) -> None:
        ...
class Adam(_Optimizer):
    def __init__(self, learning_rate: typing.SupportsFloat | typing.SupportsIndex = 0.0010000000474974513, beta1: typing.SupportsFloat | typing.SupportsIndex = 0.8999999761581421, beta2: typing.SupportsFloat | typing.SupportsIndex = 0.9990000128746033, eps: typing.SupportsFloat | typing.SupportsIndex = 9.99999993922529e-09) -> None:
        ...
class BatchNormalization(_Layer):
    def __init__(self, num_features: typing.SupportsInt | typing.SupportsIndex, momentum: typing.SupportsFloat | typing.SupportsIndex = 0.8999999761581421, eps: typing.SupportsFloat | typing.SupportsIndex = 9.999999747378752e-06) -> None:
        ...
class Dense(_Layer):
    def __init__(self, input_size: typing.SupportsInt | typing.SupportsIndex, output_size: typing.SupportsInt | typing.SupportsIndex) -> None:
        """
        A fully connected (dense) layer for a neural network.
        This layer performs a linear transformation on the input data, followed by an optional activation function.
        It maintains weights and biases as parameters, and computes gradients during backpropagation.
        """
        ...
    @property
    def input_size(self) -> int:
        ...
    @property
    def output_size(self) -> int:
        ...
class Dropout(_Layer):
    def __init__(self, drop_rate: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
class HyperparameterTuner:
    def __init__(self) -> None:
        ...
    def grid_search(self, x_train: Tensor, y_train: Tensor, x_val: Tensor, y_val: Tensor, param_grid: dict, network_builder: collections.abc.Callable, epochs: typing.SupportsInt | typing.SupportsIndex = 50, batch_size: typing.SupportsInt | typing.SupportsIndex = 32) -> dict:
        ...
class Linear(_Layer):
    """A linear layer for a neural network.
    This layer performs a linear transformation on the input data without any activation function.
    It maintains weights and biases as parameters, and computes gradients during backpropagation.
    """
    def __init__(self) -> None:
        ...
class MeanSquaredError(_LossLayer):
    def __init__(self) -> None:
        ...
class Momentum(_Optimizer):
    def __init__(self, learning_rate: typing.SupportsFloat | typing.SupportsIndex = 0.009999999776482582, momentum: typing.SupportsFloat | typing.SupportsIndex = 0.8999999761581421) -> None:
        ...
class NeuralNetwork:
    def __init__(self) -> None:
        ...
    def accuracy(self, arg0: Tensor, arg1: Tensor) -> float:
        ...
    def add_layer(self, arg0: typing.Any) -> None:
        ...
    def backward(self) -> None:
        ...
    def compute_loss(self, arg0: Tensor, arg1: Tensor, arg2: bool) -> float:
        ...
    def gradient(self) -> list:
        ...
    def load(self, arg0: str) -> None:
        ...
    def predict(self, x: Tensor, training: bool = False) -> Tensor:
        ...
    def save(self, arg0: str) -> None:
        ...
    def set_loss(self, arg0: typing.Any) -> None:
        ...
    def step(self, arg0: _Optimizer, arg1: Tensor, arg2: Tensor) -> tuple[float, float]:
        ...
    def update(self, arg0: _Optimizer) -> None:
        ...
class ReLU(_Layer):
    """A Rectified Linear Unit (ReLU) activation layer for a neural network.
    This layer applies the ReLU activation function to the input data, which sets all negative values to zero and keeps positive values unchanged.
    It computes gradients during backpropagation for training the model.
    """
    def __init__(self) -> None:
        ...
class SGD(_Optimizer):
    def __init__(self, learning_rate: typing.SupportsFloat | typing.SupportsIndex = 0.009999999776482582) -> None:
        ...
class Sigmoid(_Layer):
    def __init__(self) -> None:
        ...
class SoftmaxCrossEntropy(_LossLayer):
    def __init__(self) -> None:
        ...
class Tanh(_Layer):
    def __init__(self) -> None:
        ...
class Tensor:
    """
    A multi-dimensional array for storing numerical data.
    """
    @staticmethod
    def ones(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> Tensor:
        ...
    @staticmethod
    def random_normal(shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], mean: typing.SupportsFloat | typing.SupportsIndex = 0.0, stddev: typing.SupportsFloat | typing.SupportsIndex = 1.0) -> Tensor:
        ...
    @staticmethod
    def random_uniform(shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], low: typing.SupportsFloat | typing.SupportsIndex = 0.0, high: typing.SupportsFloat | typing.SupportsIndex = 1.0) -> Tensor:
        ...
    @staticmethod
    def zeros(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> Tensor:
        ...
    @typing.overload
    def __add__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> float:
        ...
    @typing.overload
    def __getitem__(self, arg0: tuple) -> float:
        ...
    @typing.overload
    def __init__(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        """
        Create a new Tensor with the given shape
        """
    @typing.overload
    def __init__(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        """
        Create a new Tensor with the given shape and fill value
        """
    @typing.overload
    def __init__(self, arg0: typing.Any) -> None:
        """
        Create a new Tensor from a Python list
        """
    def __len__(self) -> int:
        ...
    @typing.overload
    def __mul__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __neg__(self) -> Tensor:
        ...
    def __radd__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __rsub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __setitem__(self, arg0: tuple, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __sub__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __sub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def __truediv__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __truediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def argmax(self, axis: typing.SupportsInt | typing.SupportsIndex = 1) -> Tensor:
        ...
    def clip(self, arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def copy(self) -> Tensor:
        ...
    def exp(self) -> Tensor:
        ...
    def log(self) -> Tensor:
        ...
    def matmul(self, arg0: Tensor) -> Tensor:
        """
        Matrix multiplication of two tensors with compatible shapes using the @ operator
        """
    def max(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def mean(self) -> float:
        ...
    @typing.overload
    def mean(self, axis: typing.SupportsInt | typing.SupportsIndex, keepdims: bool = False) -> Tensor:
        ...
    def pow(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def reshape(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    def sqrt(self) -> Tensor:
        ...
    @typing.overload
    def sum(self) -> float:
        ...
    @typing.overload
    def sum(self, axis: typing.SupportsInt | typing.SupportsIndex, keepdims: bool = False) -> Tensor:
        ...
    def transpose(self) -> Tensor:
        ...
    @property
    def T(self) -> Tensor:
        ...
    @property
    def data(self) -> list:
        """
        Get the data of the Tensor as a nested list
        """
    @property
    def ndim(self) -> int:
        ...
    @property
    def shape(self) -> list:
        """
        Get the shape of the Tensor
        """
    @property
    def size(self) -> int:
        ...
class Trainer:
    def __init__(self, network: NeuralNetwork, optimizer: _Optimizer) -> None:
        ...
    def fit(self, x_train: Tensor, y_train: Tensor, x_val: Tensor, y_val: Tensor, epochs: typing.SupportsInt | typing.SupportsIndex = 100, batch_size: typing.SupportsInt | typing.SupportsIndex = 32, verbose: bool = True, print_every: typing.SupportsInt | typing.SupportsIndex = 10) -> tuple[list[float], list[float], list[float], list[float]]:
        ...
    def train_step(self, arg0: Tensor, arg1: Tensor) -> tuple[float, float]:
        ...
    @property
    def train_acc_history(self) -> list[float]:
        ...
    @property
    def train_loss_history(self) -> list[float]:
        ...
    @property
    def val_acc_history(self) -> list[float]:
        ...
    @property
    def val_loss_history(self) -> list[float]:
        ...
class _Layer:
    def backward(self, arg0: Tensor) -> Tensor:
        ...
    def forward(self, arg0: Tensor, arg1: bool) -> Tensor:
        ...
class _LossLayer:
    def backward(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def forward(self, arg0: Tensor, arg1: Tensor, arg2: bool) -> float:
        ...
class _Optimizer:
    def update(self, arg0: collections.abc.Mapping[str, Tensor], arg1: collections.abc.Mapping[str, Tensor]) -> None:
        ...
    @property
    def learning_rate(self) -> float:
        ...
    @learning_rate.setter
    def learning_rate(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
